//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: lines_longer_than_80_chars

import 'package:polaris_client/api.dart';
import 'package:test/test.dart';

// tests for ForwardGeocodingRequest
void main() {
  final instance = ForwardGeocodingRequest();

  group('test ForwardGeocodingRequest', () {
    // UUID for the request, generated by RUMBO at the time of the request.
    // String requestId
    test('to test the property `requestId`', () async {
      // TODO
    });

    // AppContext app
    test('to test the property `app`', () async {
      // TODO
    });

    // DeviceContext device
    test('to test the property `device`', () async {
      // TODO
    });

    // Freeform search text.
    // String searchText
    test('to test the property `searchText`', () async {
      // TODO
    });

    // MapViewContext mapView
    test('to test the property `mapView`', () async {
      // TODO
    });


  });

}
