//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:polaris_client/api.dart';
import 'package:test/test.dart';

// tests for LocationLookupRequest
void main() {
  final instance = LocationLookupRequest();

  group('test LocationLookupRequest', () {
    // UUID v4 for the request, generated by the caller at the time of the request
    // String requestId
    test('to test the property `requestId`', () async {
      // TODO
    });

    // A latitude value, in the range [-90, 90].
    // num lat
    test('to test the property `lat`', () async {
      // TODO
    });

    // A longitude value, in the range [-180, 180].
    // num lon
    test('to test the property `lon`', () async {
      // TODO
    });

    // CallerLocationInfo callerLocation
    test('to test the property `callerLocation`', () async {
      // TODO
    });

    // The ISO 639-1 code of the input and (preferred) output language. Note: The service does not currently distinguish between regional differences in languages, as captured by the IETF Language Tag standard At the time of writing the supported values were: en, es and th References: - https://en.wikipedia.org/wiki/IETF_language_tag - https://en.wikipedia.org/wiki/ISO_639 
    // String language
    test('to test the property `language`', () async {
      // TODO
    });


  });

}
