//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:polaris_client/api.dart';
import 'package:test/test.dart';

// tests for ReverseGeocodingRequest
void main() {
  final instance = ReverseGeocodingRequest();

  group('test ReverseGeocodingRequest', () {
    // UUID for the request, generated by RUMBO at the time of the request.
    // String requestId
    test('to test the property `requestId`', () async {
      // TODO
    });

    // AppContext app
    test('to test the property `app`', () async {
      // TODO
    });

    // GeoPosition location
    test('to test the property `location`', () async {
      // TODO
    });


  });

}
