//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of polaris;

class CommonRequest {
  /// Returns a new [CommonRequest] instance.
  CommonRequest({
    @required this.requestId,
    @required this.app,
  });

  /// UUID for the request, generated by RUMBO at the time of the request.
  String requestId;

  AppContext app;

  @override
  bool operator ==(Object other) => identical(this, other) || other is CommonRequest &&
     other.requestId == requestId &&
     other.app == app;

  @override
  int get hashCode =>
  // ignore: unnecessary_parenthesis
    (requestId == null ? 0 : requestId.hashCode) +
    (app == null ? 0 : app.hashCode);

  @override
  String toString() => 'CommonRequest[requestId=$requestId, app=$app]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'requestId'] = requestId;
      json[r'app'] = app;
    return json;
  }

  /// Returns a new [CommonRequest] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static CommonRequest fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();
      return CommonRequest(
        requestId: mapValueOfType<String>(json, r'requestId'),
        app: AppContext.fromJson(json[r'app']),
      );
    }
    return null;
  }

  static List<CommonRequest> listFromJson(dynamic json, {bool emptyIsNull, bool growable,}) =>
    json is List && json.isNotEmpty
      ? json.map(CommonRequest.fromJson).toList(growable: true == growable)
      : true == emptyIsNull ? null : <CommonRequest>[];

  static Map<String, CommonRequest> mapFromJson(dynamic json) {
    final map = <String, CommonRequest>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) => map[key] = CommonRequest.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of CommonRequest-objects as value to a dart map
  static Map<String, List<CommonRequest>> mapListFromJson(dynamic json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<CommonRequest>>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) {
          map[key] = CommonRequest.listFromJson(
            value,
            emptyIsNull: emptyIsNull,
            growable: growable,
          );
        });
    }
    return map;
  }
}

