//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class CommonRequest {
  /// Returns a new [CommonRequest] instance.
  CommonRequest({
    @required this.requestId,
    @required this.app,
  });

  /// UUID for the request, generated by RUMBO at the time of the request.
  String requestId;

  AppContext app;

  @override
  bool operator ==(Object other) => identical(this, other) || other is CommonRequest &&
     other.requestId == requestId &&
     other.app == app;

  @override
  int get hashCode =>
    (requestId == null ? 0 : requestId.hashCode) +
    (app == null ? 0 : app.hashCode);

  @override
  String toString() => 'CommonRequest[requestId=$requestId, app=$app]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'requestId'] = requestId;
      json[r'app'] = app;
    return json;
  }

  /// Returns a new [CommonRequest] instance and imports its values from
  /// [json] if it's non-null, null if [json] is null.
  static CommonRequest fromJson(Map<String, dynamic> json) => json == null
    ? null
    : CommonRequest(
        requestId: json[r'requestId'],
        app: AppContext.fromJson(json[r'app']),
    );

  static List<CommonRequest> listFromJson(List<dynamic> json, {bool emptyIsNull, bool growable,}) =>
    json == null || json.isEmpty
      ? true == emptyIsNull ? null : <CommonRequest>[]
      : json.map((dynamic value) => CommonRequest.fromJson(value)).toList(growable: true == growable);

  static Map<String, CommonRequest> mapFromJson(Map<String, dynamic> json) {
    final map = <String, CommonRequest>{};
    if (json?.isNotEmpty == true) {
      json.forEach((key, value) => map[key] = CommonRequest.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of CommonRequest-objects as value to a dart map
  static Map<String, List<CommonRequest>> mapListFromJson(Map<String, dynamic> json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<CommonRequest>>{};
    if (json?.isNotEmpty == true) {
      json.forEach((key, value) {
        map[key] = CommonRequest.listFromJson(value, emptyIsNull: emptyIsNull, growable: growable,);
      });
    }
    return map;
  }
}

