part of openapi.api;

class CommonRequest {
  /* UUID for the request, generated by RUMBO at the time of the request. */
  String requestId = null;

  AppContext app = null;
  CommonRequest();

  @override
  String toString() {
    return 'CommonRequest[requestId=$requestId, app=$app, ]';
  }

  CommonRequest.fromJson(Map<String, dynamic> json) {
    if (json == null) return;
    requestId = json['requestId'];
    app = (json['app'] == null) ? null : AppContext.fromJson(json['app']);
  }

  Map<String, dynamic> toJson() {
    Map<String, dynamic> json = {};
    if (requestId != null) json['requestId'] = requestId;
    if (app != null) json['app'] = app;
    return json;
  }

  static List<CommonRequest> listFromJson(List<dynamic> json) {
    return json == null
        ? <CommonRequest>[]
        : json.map((value) => CommonRequest.fromJson(value)).toList();
  }

  static Map<String, CommonRequest> mapFromJson(Map<String, dynamic> json) {
    var map = Map<String, CommonRequest>();
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = CommonRequest.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of CommonRequest-objects as value to a dart map
  static Map<String, List<CommonRequest>> mapListFromJson(
      Map<String, dynamic> json) {
    var map = Map<String, List<CommonRequest>>();
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) {
        map[key] = CommonRequest.listFromJson(value);
      });
    }
    return map;
  }
}
