//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of polaris;

class CommonResponse {
  /// Returns a new [CommonResponse] instance.
  CommonResponse({
    @required this.requestId,
  });

  /// UUID for the request, generated by RUMBO at the time of the request.
  String requestId;

  @override
  bool operator ==(Object other) => identical(this, other) || other is CommonResponse &&
     other.requestId == requestId;

  @override
  int get hashCode =>
  // ignore: unnecessary_parenthesis
    (requestId == null ? 0 : requestId.hashCode);

  @override
  String toString() => 'CommonResponse[requestId=$requestId]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'requestId'] = requestId;
    return json;
  }

  /// Returns a new [CommonResponse] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static CommonResponse fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();
      return CommonResponse(
        requestId: mapValueOfType<String>(json, r'requestId'),
      );
    }
    return null;
  }

  static List<CommonResponse> listFromJson(dynamic json, {bool emptyIsNull, bool growable,}) =>
    json is List && json.isNotEmpty
      ? json.map(CommonResponse.fromJson).toList(growable: true == growable)
      : true == emptyIsNull ? null : <CommonResponse>[];

  static Map<String, CommonResponse> mapFromJson(dynamic json) {
    final map = <String, CommonResponse>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) => map[key] = CommonResponse.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of CommonResponse-objects as value to a dart map
  static Map<String, List<CommonResponse>> mapListFromJson(dynamic json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<CommonResponse>>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) {
          map[key] = CommonResponse.listFromJson(
            value,
            emptyIsNull: emptyIsNull,
            growable: growable,
          );
        });
    }
    return map;
  }
}

