//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class CommonResponse {
  /// Returns a new [CommonResponse] instance.
  CommonResponse({
    @required this.requestId,
  });

  /// UUID for the request, generated by RUMBO at the time of the request.
  String requestId;

  @override
  bool operator ==(Object other) => identical(this, other) || other is CommonResponse &&
     other.requestId == requestId;

  @override
  int get hashCode =>
    (requestId == null ? 0 : requestId.hashCode);

  @override
  String toString() => 'CommonResponse[requestId=$requestId]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'requestId'] = requestId;
    return json;
  }

  /// Returns a new [CommonResponse] instance and imports its values from
  /// [json] if it's non-null, null if [json] is null.
  static CommonResponse fromJson(Map<String, dynamic> json) => json == null
    ? null
    : CommonResponse(
        requestId: json[r'requestId'],
    );

  static List<CommonResponse> listFromJson(List<dynamic> json, {bool emptyIsNull, bool growable,}) =>
    json == null || json.isEmpty
      ? true == emptyIsNull ? null : <CommonResponse>[]
      : json.map((dynamic value) => CommonResponse.fromJson(value)).toList(growable: true == growable);

  static Map<String, CommonResponse> mapFromJson(Map<String, dynamic> json) {
    final map = <String, CommonResponse>{};
    if (json?.isNotEmpty == true) {
      json.forEach((key, value) => map[key] = CommonResponse.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of CommonResponse-objects as value to a dart map
  static Map<String, List<CommonResponse>> mapListFromJson(Map<String, dynamic> json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<CommonResponse>>{};
    if (json?.isNotEmpty == true) {
      json.forEach((key, value) {
        map[key] = CommonResponse.listFromJson(value, emptyIsNull: emptyIsNull, growable: growable,);
      });
    }
    return map;
  }
}

