part of openapi.api;

class CommonResponse {
  /* UUID for the request, generated by RUMBO at the time of the request. */
  String requestId = null;

  ServiceContext service = null;
  CommonResponse();

  @override
  String toString() {
    return 'CommonResponse[requestId=$requestId, service=$service, ]';
  }

  CommonResponse.fromJson(Map<String, dynamic> json) {
    if (json == null) return;
    requestId = json['requestId'];
    service = (json['service'] == null)
        ? null
        : ServiceContext.fromJson(json['service']);
  }

  Map<String, dynamic> toJson() {
    Map<String, dynamic> json = {};
    if (requestId != null) json['requestId'] = requestId;
    if (service != null) json['service'] = service;
    return json;
  }

  static List<CommonResponse> listFromJson(List<dynamic> json) {
    return json == null
        ? <CommonResponse>[]
        : json.map((value) => CommonResponse.fromJson(value)).toList();
  }

  static Map<String, CommonResponse> mapFromJson(Map<String, dynamic> json) {
    var map = Map<String, CommonResponse>();
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = CommonResponse.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of CommonResponse-objects as value to a dart map
  static Map<String, List<CommonResponse>> mapListFromJson(
      Map<String, dynamic> json) {
    var map = Map<String, List<CommonResponse>>();
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) {
        map[key] = CommonResponse.listFromJson(value);
      });
    }
    return map;
  }
}
