part of openapi.api;

class ForwardGeocodingResponse {
  /* UUID for the request, generated by RUMBO at the time of the request. */
  String requestId = null;

  ServiceContext service = null;

  List<PlaceItem> results = [];
  ForwardGeocodingResponse();

  @override
  String toString() {
    return 'ForwardGeocodingResponse[requestId=$requestId, service=$service, results=$results, ]';
  }

  ForwardGeocodingResponse.fromJson(Map<String, dynamic> json) {
    if (json == null) return;
    requestId = json['requestId'];
    service = (json['service'] == null)
        ? null
        : ServiceContext.fromJson(json['service']);
    results = (json['results'] == null)
        ? null
        : PlaceItem.listFromJson(json['results']);
  }

  Map<String, dynamic> toJson() {
    Map<String, dynamic> json = {};
    if (requestId != null) json['requestId'] = requestId;
    if (service != null) json['service'] = service;
    if (results != null) json['results'] = results;
    return json;
  }

  static List<ForwardGeocodingResponse> listFromJson(List<dynamic> json) {
    return json == null
        ? <ForwardGeocodingResponse>[]
        : json
            .map((value) => ForwardGeocodingResponse.fromJson(value))
            .toList();
  }

  static Map<String, ForwardGeocodingResponse> mapFromJson(
      Map<String, dynamic> json) {
    var map = Map<String, ForwardGeocodingResponse>();
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = ForwardGeocodingResponse.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of ForwardGeocodingResponse-objects as value to a dart map
  static Map<String, List<ForwardGeocodingResponse>> mapListFromJson(
      Map<String, dynamic> json) {
    var map = Map<String, List<ForwardGeocodingResponse>>();
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) {
        map[key] = ForwardGeocodingResponse.listFromJson(value);
      });
    }
    return map;
  }
}
