//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class ForwardGeocodingResponse {
  /// Returns a new [ForwardGeocodingResponse] instance.
  ForwardGeocodingResponse({
    @required this.requestId,
    this.results = const [],
  });

  /// UUID for the request, generated by RUMBO at the time of the request.
  String requestId;

  List<PlaceItem> results;

  @override
  bool operator ==(Object other) => identical(this, other) || other is ForwardGeocodingResponse &&
     other.requestId == requestId &&
     other.results == results;

  @override
  int get hashCode =>
    (requestId == null ? 0 : requestId.hashCode) +
    (results == null ? 0 : results.hashCode);

  @override
  String toString() => 'ForwardGeocodingResponse[requestId=$requestId, results=$results]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'requestId'] = requestId;
      json[r'results'] = results;
    return json;
  }

  /// Returns a new [ForwardGeocodingResponse] instance and imports its values from
  /// [json] if it's non-null, null if [json] is null.
  static ForwardGeocodingResponse fromJson(Map<String, dynamic> json) => json == null
    ? null
    : ForwardGeocodingResponse(
        requestId: json[r'requestId'],
        results: PlaceItem.listFromJson(json[r'results']),
    );

  static List<ForwardGeocodingResponse> listFromJson(List<dynamic> json, {bool emptyIsNull, bool growable,}) =>
    json == null || json.isEmpty
      ? true == emptyIsNull ? null : <ForwardGeocodingResponse>[]
      : json.map((dynamic value) => ForwardGeocodingResponse.fromJson(value)).toList(growable: true == growable);

  static Map<String, ForwardGeocodingResponse> mapFromJson(Map<String, dynamic> json) {
    final map = <String, ForwardGeocodingResponse>{};
    if (json?.isNotEmpty == true) {
      json.forEach((key, value) => map[key] = ForwardGeocodingResponse.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of ForwardGeocodingResponse-objects as value to a dart map
  static Map<String, List<ForwardGeocodingResponse>> mapListFromJson(Map<String, dynamic> json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<ForwardGeocodingResponse>>{};
    if (json?.isNotEmpty == true) {
      json.forEach((key, value) {
        map[key] = ForwardGeocodingResponse.listFromJson(value, emptyIsNull: emptyIsNull, growable: growable,);
      });
    }
    return map;
  }
}

