part of openapi.api;

class ForwardGeocodingRequest {
  /* UUID for the request, generated by RUMBO at the time of the request. */
  String requestId = null;

  AppContext app = null;

  DeviceContext device = null;
  /* Freeform search text. */
  String searchText = null;

  MapViewContext mapView = null;
  ForwardGeocodingRequest();

  @override
  String toString() {
    return 'ForwardGeocodingRequest[requestId=$requestId, app=$app, device=$device, searchText=$searchText, mapView=$mapView, ]';
  }

  ForwardGeocodingRequest.fromJson(Map<String, dynamic> json) {
    if (json == null) return;
    requestId = json['requestId'];
    app = (json['app'] == null) ? null : AppContext.fromJson(json['app']);
    device = (json['device'] == null)
        ? null
        : DeviceContext.fromJson(json['device']);
    searchText = json['searchText'];
    mapView = (json['mapView'] == null)
        ? null
        : MapViewContext.fromJson(json['mapView']);
  }

  Map<String, dynamic> toJson() {
    Map<String, dynamic> json = {};
    if (requestId != null) json['requestId'] = requestId;
    if (app != null) json['app'] = app;
    if (device != null) json['device'] = device;
    if (searchText != null) json['searchText'] = searchText;
    if (mapView != null) json['mapView'] = mapView;
    return json;
  }

  static List<ForwardGeocodingRequest> listFromJson(List<dynamic> json) {
    return json == null
        ? <ForwardGeocodingRequest>[]
        : json.map((value) => ForwardGeocodingRequest.fromJson(value)).toList();
  }

  static Map<String, ForwardGeocodingRequest> mapFromJson(
      Map<String, dynamic> json) {
    var map = Map<String, ForwardGeocodingRequest>();
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = ForwardGeocodingRequest.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of ForwardGeocodingRequest-objects as value to a dart map
  static Map<String, List<ForwardGeocodingRequest>> mapListFromJson(
      Map<String, dynamic> json) {
    var map = Map<String, List<ForwardGeocodingRequest>>();
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) {
        map[key] = ForwardGeocodingRequest.listFromJson(value);
      });
    }
    return map;
  }
}
