//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of polaris;

class ForwardGeocodingResponse {
  /// Returns a new [ForwardGeocodingResponse] instance.
  ForwardGeocodingResponse({
    @required this.requestId,
    this.results = const [],
  });

  /// UUID for the request, generated by RUMBO at the time of the request.
  String requestId;

  List<PlaceItem> results;

  @override
  bool operator ==(Object other) => identical(this, other) || other is ForwardGeocodingResponse &&
     other.requestId == requestId &&
     other.results == results;

  @override
  int get hashCode =>
  // ignore: unnecessary_parenthesis
    (requestId == null ? 0 : requestId.hashCode) +
    (results == null ? 0 : results.hashCode);

  @override
  String toString() => 'ForwardGeocodingResponse[requestId=$requestId, results=$results]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'requestId'] = requestId;
      json[r'results'] = results;
    return json;
  }

  /// Returns a new [ForwardGeocodingResponse] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static ForwardGeocodingResponse fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();
      return ForwardGeocodingResponse(
        requestId: mapValueOfType<String>(json, r'requestId'),
        results: PlaceItem.listFromJson(json[r'results']),
      );
    }
    return null;
  }

  static List<ForwardGeocodingResponse> listFromJson(dynamic json, {bool emptyIsNull, bool growable,}) =>
    json is List && json.isNotEmpty
      ? json.map(ForwardGeocodingResponse.fromJson).toList(growable: true == growable)
      : true == emptyIsNull ? null : <ForwardGeocodingResponse>[];

  static Map<String, ForwardGeocodingResponse> mapFromJson(dynamic json) {
    final map = <String, ForwardGeocodingResponse>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) => map[key] = ForwardGeocodingResponse.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of ForwardGeocodingResponse-objects as value to a dart map
  static Map<String, List<ForwardGeocodingResponse>> mapListFromJson(dynamic json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<ForwardGeocodingResponse>>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) {
          map[key] = ForwardGeocodingResponse.listFromJson(
            value,
            emptyIsNull: emptyIsNull,
            growable: growable,
          );
        });
    }
    return map;
  }
}

