//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class ForwardGeocodingRequest {
  /// Returns a new [ForwardGeocodingRequest] instance.
  ForwardGeocodingRequest({
    @required this.requestId,
    @required this.app,
    @required this.device,
    @required this.searchText,
    this.mapView,
  });

  /// UUID for the request, generated by RUMBO at the time of the request.
  String requestId;

  AppContext app;

  DeviceContext device;

  /// Freeform search text.
  String searchText;

  MapViewContext mapView;

  @override
  bool operator ==(Object other) => identical(this, other) || other is ForwardGeocodingRequest &&
     other.requestId == requestId &&
     other.app == app &&
     other.device == device &&
     other.searchText == searchText &&
     other.mapView == mapView;

  @override
  int get hashCode =>
    (requestId == null ? 0 : requestId.hashCode) +
    (app == null ? 0 : app.hashCode) +
    (device == null ? 0 : device.hashCode) +
    (searchText == null ? 0 : searchText.hashCode) +
    (mapView == null ? 0 : mapView.hashCode);

  @override
  String toString() => 'ForwardGeocodingRequest[requestId=$requestId, app=$app, device=$device, searchText=$searchText, mapView=$mapView]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'requestId'] = requestId;
      json[r'app'] = app;
      json[r'device'] = device;
      json[r'searchText'] = searchText;
    if (mapView != null) {
      json[r'mapView'] = mapView;
    }
    return json;
  }

  /// Returns a new [ForwardGeocodingRequest] instance and imports its values from
  /// [json] if it's non-null, null if [json] is null.
  static ForwardGeocodingRequest fromJson(Map<String, dynamic> json) => json == null
    ? null
    : ForwardGeocodingRequest(
        requestId: json[r'requestId'],
        app: AppContext.fromJson(json[r'app']),
        device: DeviceContext.fromJson(json[r'device']),
        searchText: json[r'searchText'],
        mapView: MapViewContext.fromJson(json[r'mapView']),
    );

  static List<ForwardGeocodingRequest> listFromJson(List<dynamic> json, {bool emptyIsNull, bool growable,}) =>
    json == null || json.isEmpty
      ? true == emptyIsNull ? null : <ForwardGeocodingRequest>[]
      : json.map((dynamic value) => ForwardGeocodingRequest.fromJson(value)).toList(growable: true == growable);

  static Map<String, ForwardGeocodingRequest> mapFromJson(Map<String, dynamic> json) {
    final map = <String, ForwardGeocodingRequest>{};
    if (json?.isNotEmpty == true) {
      json.forEach((key, value) => map[key] = ForwardGeocodingRequest.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of ForwardGeocodingRequest-objects as value to a dart map
  static Map<String, List<ForwardGeocodingRequest>> mapListFromJson(Map<String, dynamic> json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<ForwardGeocodingRequest>>{};
    if (json?.isNotEmpty == true) {
      json.forEach((key, value) {
        map[key] = ForwardGeocodingRequest.listFromJson(value, emptyIsNull: emptyIsNull, growable: growable,);
      });
    }
    return map;
  }
}

