//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of polaris;

class LocationLookupRequest {
  /// Returns a new [LocationLookupRequest] instance.
  LocationLookupRequest({
    @required this.requestId,
    @required this.lat,
    @required this.lon,
    this.callerLocation,
    @required this.language,
  });

  /// UUID v4 for the request, generated by the caller at the time of the request
  String requestId;

  /// A latitude value, in the range [-90, 90].
  // minimum: -90
  // maximum: 90
  num lat;

  /// A longitude value, in the range [-180, 180].
  // minimum: -180
  // maximum: 180
  num lon;

  CallerLocationInfo callerLocation;

  /// The ISO 639-1 code of the input and (preferred) output language. Note: The service does not currently distinguish between regional differences in languages, as captured by the IETF Language Tag standard At the time of writing the supported values were: en, es and th References: - https://en.wikipedia.org/wiki/IETF_language_tag - https://en.wikipedia.org/wiki/ISO_639 
  String language;

  @override
  bool operator ==(Object other) => identical(this, other) || other is LocationLookupRequest &&
     other.requestId == requestId &&
     other.lat == lat &&
     other.lon == lon &&
     other.callerLocation == callerLocation &&
     other.language == language;

  @override
  int get hashCode =>
  // ignore: unnecessary_parenthesis
    (requestId == null ? 0 : requestId.hashCode) +
    (lat == null ? 0 : lat.hashCode) +
    (lon == null ? 0 : lon.hashCode) +
    (callerLocation == null ? 0 : callerLocation.hashCode) +
    (language == null ? 0 : language.hashCode);

  @override
  String toString() => 'LocationLookupRequest[requestId=$requestId, lat=$lat, lon=$lon, callerLocation=$callerLocation, language=$language]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'requestId'] = requestId;
      json[r'lat'] = lat;
      json[r'lon'] = lon;
    if (callerLocation != null) {
      json[r'callerLocation'] = callerLocation;
    }
      json[r'language'] = language;
    return json;
  }

  /// Returns a new [LocationLookupRequest] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static LocationLookupRequest fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();
      return LocationLookupRequest(
        requestId: mapValueOfType<String>(json, r'requestId'),
        lat: json[r'lat'] == null
          ? null
          : num.parse(json[r'lat'].toString()),
        lon: json[r'lon'] == null
          ? null
          : num.parse(json[r'lon'].toString()),
        callerLocation: CallerLocationInfo.fromJson(json[r'callerLocation']),
        language: mapValueOfType<String>(json, r'language'),
      );
    }
    return null;
  }

  static List<LocationLookupRequest> listFromJson(dynamic json, {bool emptyIsNull, bool growable,}) =>
    json is List && json.isNotEmpty
      ? json.map(LocationLookupRequest.fromJson).toList(growable: true == growable)
      : true == emptyIsNull ? null : <LocationLookupRequest>[];

  static Map<String, LocationLookupRequest> mapFromJson(dynamic json) {
    final map = <String, LocationLookupRequest>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) => map[key] = LocationLookupRequest.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of LocationLookupRequest-objects as value to a dart map
  static Map<String, List<LocationLookupRequest>> mapListFromJson(dynamic json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<LocationLookupRequest>>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) {
          map[key] = LocationLookupRequest.listFromJson(
            value,
            emptyIsNull: emptyIsNull,
            growable: growable,
          );
        });
    }
    return map;
  }
}

