//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of polaris;

class PlaceSearchRequestAllOf {
  /// Returns a new [PlaceSearchRequestAllOf] instance.
  PlaceSearchRequestAllOf({
    @required this.query,
    this.callerLocation,
    @required this.sessionToken,
    @required this.language,
  });

  /// An updated query string for the current search session. It _must_ start with the same characters specified when the search session was started, and have at least 1 extra character. 
  String query;

  CallerLocationInfo callerLocation;

  /// A string containing a UUID v4 generated by the caller. This token is used to group search requests with  requests to fetch the details of a candidate result.  If no active token exists, the caller should generate one and use it until it becomes \"consumed\". A token becomes consumed once a call is made to fetch the details for a candidate result. The token must no longer be  used for subsequent searches, even if they are further refinements of the current search string. NOTE: Reusing a token for unrelated searches and/or place detail lookups has undefined behaviour. 
  String sessionToken;

  /// The ISO 639-1 code of the input and (preferred) output language. Note: The service does not currently distinguish between regional differences in languages, as captured by the IETF Language Tag standard At the time of writing the supported values were: en, es and th References: - https://en.wikipedia.org/wiki/IETF_language_tag - https://en.wikipedia.org/wiki/ISO_639 
  String language;

  @override
  bool operator ==(Object other) => identical(this, other) || other is PlaceSearchRequestAllOf &&
     other.query == query &&
     other.callerLocation == callerLocation &&
     other.sessionToken == sessionToken &&
     other.language == language;

  @override
  int get hashCode =>
  // ignore: unnecessary_parenthesis
    (query == null ? 0 : query.hashCode) +
    (callerLocation == null ? 0 : callerLocation.hashCode) +
    (sessionToken == null ? 0 : sessionToken.hashCode) +
    (language == null ? 0 : language.hashCode);

  @override
  String toString() => 'PlaceSearchRequestAllOf[query=$query, callerLocation=$callerLocation, sessionToken=$sessionToken, language=$language]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'query'] = query;
    if (callerLocation != null) {
      json[r'callerLocation'] = callerLocation;
    }
      json[r'sessionToken'] = sessionToken;
      json[r'language'] = language;
    return json;
  }

  /// Returns a new [PlaceSearchRequestAllOf] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static PlaceSearchRequestAllOf fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();
      return PlaceSearchRequestAllOf(
        query: mapValueOfType<String>(json, r'query'),
        callerLocation: CallerLocationInfo.fromJson(json[r'callerLocation']),
        sessionToken: mapValueOfType<String>(json, r'sessionToken'),
        language: mapValueOfType<String>(json, r'language'),
      );
    }
    return null;
  }

  static List<PlaceSearchRequestAllOf> listFromJson(dynamic json, {bool emptyIsNull, bool growable,}) =>
    json is List && json.isNotEmpty
      ? json.map(PlaceSearchRequestAllOf.fromJson).toList(growable: true == growable)
      : true == emptyIsNull ? null : <PlaceSearchRequestAllOf>[];

  static Map<String, PlaceSearchRequestAllOf> mapFromJson(dynamic json) {
    final map = <String, PlaceSearchRequestAllOf>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) => map[key] = PlaceSearchRequestAllOf.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of PlaceSearchRequestAllOf-objects as value to a dart map
  static Map<String, List<PlaceSearchRequestAllOf>> mapListFromJson(dynamic json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<PlaceSearchRequestAllOf>>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) {
          map[key] = PlaceSearchRequestAllOf.listFromJson(
            value,
            emptyIsNull: emptyIsNull,
            growable: growable,
          );
        });
    }
    return map;
  }
}

