part of openapi.api;

class ReverseGeocodingRequest {
  /* UUID for the request, generated by RUMBO at the time of the request. */
  String requestId = null;

  AppContext app = null;

  GeoPosition location = null;
  ReverseGeocodingRequest();

  @override
  String toString() {
    return 'ReverseGeocodingRequest[requestId=$requestId, app=$app, location=$location, ]';
  }

  ReverseGeocodingRequest.fromJson(Map<String, dynamic> json) {
    if (json == null) return;
    requestId = json['requestId'];
    app = (json['app'] == null) ? null : AppContext.fromJson(json['app']);
    location = (json['location'] == null)
        ? null
        : GeoPosition.fromJson(json['location']);
  }

  Map<String, dynamic> toJson() {
    Map<String, dynamic> json = {};
    if (requestId != null) json['requestId'] = requestId;
    if (app != null) json['app'] = app;
    if (location != null) json['location'] = location;
    return json;
  }

  static List<ReverseGeocodingRequest> listFromJson(List<dynamic> json) {
    return json == null
        ? <ReverseGeocodingRequest>[]
        : json.map((value) => ReverseGeocodingRequest.fromJson(value)).toList();
  }

  static Map<String, ReverseGeocodingRequest> mapFromJson(
      Map<String, dynamic> json) {
    var map = Map<String, ReverseGeocodingRequest>();
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) =>
          map[key] = ReverseGeocodingRequest.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of ReverseGeocodingRequest-objects as value to a dart map
  static Map<String, List<ReverseGeocodingRequest>> mapListFromJson(
      Map<String, dynamic> json) {
    var map = Map<String, List<ReverseGeocodingRequest>>();
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) {
        map[key] = ReverseGeocodingRequest.listFromJson(value);
      });
    }
    return map;
  }
}
