//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class ReverseGeocodingRequest {
  /// Returns a new [ReverseGeocodingRequest] instance.
  ReverseGeocodingRequest({
    @required this.requestId,
    @required this.app,
    @required this.location,
  });

  /// UUID for the request, generated by RUMBO at the time of the request.
  String requestId;

  AppContext app;

  GeoPosition location;

  @override
  bool operator ==(Object other) => identical(this, other) || other is ReverseGeocodingRequest &&
     other.requestId == requestId &&
     other.app == app &&
     other.location == location;

  @override
  int get hashCode =>
    (requestId == null ? 0 : requestId.hashCode) +
    (app == null ? 0 : app.hashCode) +
    (location == null ? 0 : location.hashCode);

  @override
  String toString() => 'ReverseGeocodingRequest[requestId=$requestId, app=$app, location=$location]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'requestId'] = requestId;
      json[r'app'] = app;
      json[r'location'] = location;
    return json;
  }

  /// Returns a new [ReverseGeocodingRequest] instance and imports its values from
  /// [json] if it's non-null, null if [json] is null.
  static ReverseGeocodingRequest fromJson(Map<String, dynamic> json) => json == null
    ? null
    : ReverseGeocodingRequest(
        requestId: json[r'requestId'],
        app: AppContext.fromJson(json[r'app']),
        location: GeoPosition.fromJson(json[r'location']),
    );

  static List<ReverseGeocodingRequest> listFromJson(List<dynamic> json, {bool emptyIsNull, bool growable,}) =>
    json == null || json.isEmpty
      ? true == emptyIsNull ? null : <ReverseGeocodingRequest>[]
      : json.map((dynamic value) => ReverseGeocodingRequest.fromJson(value)).toList(growable: true == growable);

  static Map<String, ReverseGeocodingRequest> mapFromJson(Map<String, dynamic> json) {
    final map = <String, ReverseGeocodingRequest>{};
    if (json?.isNotEmpty == true) {
      json.forEach((key, value) => map[key] = ReverseGeocodingRequest.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of ReverseGeocodingRequest-objects as value to a dart map
  static Map<String, List<ReverseGeocodingRequest>> mapListFromJson(Map<String, dynamic> json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<ReverseGeocodingRequest>>{};
    if (json?.isNotEmpty == true) {
      json.forEach((key, value) {
        map[key] = ReverseGeocodingRequest.listFromJson(value, emptyIsNull: emptyIsNull, growable: growable,);
      });
    }
    return map;
  }
}

