//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of polaris;

class ServiceRequest {
  /// Returns a new [ServiceRequest] instance.
  ServiceRequest({
    @required this.requestId,
  });

  /// UUID v4 for the request, generated by the caller at the time of the request
  String requestId;

  @override
  bool operator ==(Object other) => identical(this, other) || other is ServiceRequest &&
     other.requestId == requestId;

  @override
  int get hashCode =>
  // ignore: unnecessary_parenthesis
    (requestId == null ? 0 : requestId.hashCode);

  @override
  String toString() => 'ServiceRequest[requestId=$requestId]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'requestId'] = requestId;
    return json;
  }

  /// Returns a new [ServiceRequest] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static ServiceRequest fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();
      return ServiceRequest(
        requestId: mapValueOfType<String>(json, r'requestId'),
      );
    }
    return null;
  }

  static List<ServiceRequest> listFromJson(dynamic json, {bool emptyIsNull, bool growable,}) =>
    json is List && json.isNotEmpty
      ? json.map(ServiceRequest.fromJson).toList(growable: true == growable)
      : true == emptyIsNull ? null : <ServiceRequest>[];

  static Map<String, ServiceRequest> mapFromJson(dynamic json) {
    final map = <String, ServiceRequest>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) => map[key] = ServiceRequest.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of ServiceRequest-objects as value to a dart map
  static Map<String, List<ServiceRequest>> mapListFromJson(dynamic json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<ServiceRequest>>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) {
          map[key] = ServiceRequest.listFromJson(
            value,
            emptyIsNull: emptyIsNull,
            growable: growable,
          );
        });
    }
    return map;
  }
}

